AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - bin/*
    - node_modules/node-sass/src/libsass/contrib/libsass.spec

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 170

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false  

Style/GlobalVars:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 150
  
Naming/PredicateName:
  Enabled: false

Style/GuardClause:
  Enabled: false  
  
Metrics/AbcSize:
  Enabled: false  

Style/MixinUsage:
  Enabled: false  

Lint/AmbiguousOperator:
  Enabled: false  
