AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - bin/*

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 125

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 90  